GhostPangPang/GhostPong

backend/package.json
backend/src/entity/README.md
backend/src/entity/achievement.entity.ts
backend/src/entity/auth.entity.ts
backend/src/entity/blocked-user.entity.ts
backend/src/entity/friendship.entity.ts
backend/src/entity/game-history.entity.ts
backend/src/entity/message-view.entity.ts
backend/src/entity/message.entity.ts
backend/src/entity/user-record.entity.ts
backend/src/entity/user.entity.ts
database/create-table.sql
docker-compose.yml

- postgreSQL 초기 설정 및 도커 설정.
- typeORM 과 연동하기 위한 entity 파일 생성.
- TypeORM 과 db 연결해서 사용하기 위한 entity file 정의.
- 모든 foreign constraint 적용, cascade 는 적용안함.
- postgres container 올리는 `docker-compose.yml` 작성
- yarn 커맨드로 `docker compose up` 가능하도록 `package.json` 파일 수정
- `yarn db`, `yarn db:down`, `yarn db:reset`
- 초기 DB 테이블 생성하는 `create-table.sql` 파일 추가
`backend` 디렉토리 안에서 실행해주세요.
- `yarn db`
- `psql -U username -d dbname -f ../database/create-table.sql`
- `psql` 은 설치가 필요할 수 있습니다. `brew install psql`
- `yarn run start`
- #16

💚 [Chore] Dockerize postgreSQL

---

backend/src/entity/achievement.entity.ts
backend/src/entity/auth.entity.ts
backend/src/entity/blocked-user.entity.ts
backend/src/entity/friendship.entity.ts
backend/src/entity/game-history.entity.ts
backend/src/entity/message-view.entity.ts
backend/src/entity/message.entity.ts
backend/src/entity/user-record.entity.ts
backend/src/entity/user.entity.ts
database/create-table.sql

- 기존 entity 파일의 관계 정의에 있던 문제를 수정했습니다. 
- 기존 entity 에서는 실제 물리 테이블처럼 foreign key 를 그대로 객체 property 로 작성했으나 이러면 이슈에서 언급한 것 같이 쓸데없는 _id 가 뒤에 붙습니다.
- 식별 관계에서는 foreign/primary key 가 실제로는 같아야 하는데 다른 column 으로 취급되면서 복제되는 문제가 생겼습니다.
- 일반 다대일 관계는 Many 쪽 칼럼을 One 쪽 객체 타입으로 바꾸고 식별관계에서는 `@ManyToOne()` 에 `@JoinColumn()` 을 명시해서 foreign 및 primary key 가 한 칼럼에 적용되도록 변경했습니다.
- 관계 테이블을 join 할 때 추가로 property 정의가 필요할 수도 있습니다. (거의 확실합니다.) 구현하면서 필요하실 때 추가하는 방식으로 하시면 좋을 것 같습니다.
- 실제로 생성되는 칼럼들은 논리 테이블 구조와 동일합니다!
- 더 자세한 문제와 해결방식은 [위키](https://www.notion.so/TypeORM-entity-d710e5dfa7e046daae5ff8c366f1d5e5?pvs=4) 에 작성하겠습니다~!
- close #44

🐛 [BugFix] fix entity relations

---

backend/.eslintrc.js
backend/package.json
backend/src/app.module.ts
backend/src/common/constant.ts
backend/src/common/dto/error-response.dto.ts
backend/src/common/dto/sucess-response.dto.ts
backend/src/entity/auth.entity.ts
backend/src/entity/friendship.entity.ts
backend/src/entity/message-view.entity.ts
backend/src/entity/user.entity.ts
backend/src/friend/friend.controller.spec.ts
backend/src/friend/friend.controller.ts
backend/src/friend/friend.module.ts
backend/src/friend/friend.service.spec.ts
backend/src/friend/friend.service.ts
backend/src/main.ts
backend/yarn.lock

- friend 도메인의 친구 신청 api 구현.
- `POST /friend?nickname=`
- `POST /friend/{userId}`
- 친구 신청하는 두 개의 api 컨트롤러와 서비스를 구현하였습니다.
- common/dto 에 모든 api 에서 사용하는 `SuccessResponseDto` 와 사실은 exception filter 에서 처리해서 리턴하기 떄문에 구현상에서는 필요없지만 swagger 에서 type 명시를 위해 사용하는 `ErrorResponseDto` 클래스를 정의했습니다. 
- auth 로직이 없기 때문에 "나의 id" 를 넣는 `x-my-id` 를 임시 헤더로 받도록 설정했습니다.
- 컨트롤러당 swagger 이것저것 설정.... 더 필요한 부분 있으면 연락주세용..
- entity 에 unique 설정 추가.
- eslint 에 규칙을 추가.
- validtation pipe 를 global 으로 설정하는 코드를 `main.ts` 에 추가.
- close #42

✨ [Feature] friend request api

---

backend/src/common/dto/success-response.dto.ts
backend/src/friend/dto/requested-friend-response.dto.ts
backend/src/friend/friend.controller.ts
backend/src/friend/friend.service.ts

- 받은 친구 신청 리스트를 가져오는 api 구현
- `GET /request` api 를 구현.
- `.map` 을 최대한 쓰고 싶지 않았는데.. typeORM 수준에서 `Friendship` 정보를 포함하지 않고 `User` 만 가져오기가 안됩니다...ㅋㅋㅋㅋㅋㅋ 자세한 것은 [위키](https://www.notion.so/TypeORM-dddebaecb5794479944454e1312fbf7d?pvs=4) 에 설명해두었습니다...
- `SuccessResponseDto` 가 있는 파일 명을 `success-response.dto.ts` 로 수정했습니다.
- 넘 자잘한 것 같아 다음 pr 은 친구 신청 수락 + 거절 합쳐서 하나로 만들어 날리도록 하겠습니다...!^^
close #57

✨ [Feature] friend get requests api

---

backend/src/app.module.ts
backend/src/user/dto/meta-info-response.dto.ts
backend/src/user/user.controller.spec.ts
backend/src/user/user.controller.ts
backend/src/user/user.module.ts
backend/src/user/user.service.spec.ts
backend/src/user/user.service.ts
database/test-data.sql

- 로그인한 유저의 메타데이터 가져오는 API 구현
- `GET /user` api 구현
- typeORM 어렵네요... 일단 양식에 맞춰 blockedUser의 id, 즉 숫자 배열만 주기 위해서 QueryBuilder로 뽑은 엔티티에서 다시 필요한 id만 뽑아내는 로직을 넣었습니다. 만일 blocked 한 user가 없다면 빈배열을 주도록 의도했습니다. repository 제공 메서드이던 QueryBuilder이던 원하는 컬럼값만 예쁘게 뽑고 싶었는데 뭐로하던 객체로 한번 감싸서 나오더라구요....만일 원하는 컬러만 예쁘게 뽑아내는 법을 아신다면 제발 알려줍쇼....
- 아 그리고 편의를 위해 test용 db data를 넣는 sql문을 test-data.sql에 넣어놨습니다. 앞으로도 추가할 예정입니다. 참고하십쇼들!!!
close #61

✨ [Feature] get user-meta-info api

---

backend/src/app.module.ts
backend/src/blocked/blocked.controller.spec.ts
backend/src/blocked/blocked.controller.ts
backend/src/blocked/blocked.module.ts
backend/src/blocked/blocked.service.spec.ts
backend/src/blocked/blocked.service.ts
backend/src/common/constant.ts
backend/src/user/user.service.ts

유저를 차단하는 API 구현
두 api에 대한 로직이 매우 흡사하여 한번에 pr 합니다.
- `blocked/{user_id}` 구현
- userService에 구현한 findExistUser를 가져다 썼습니다. 그런데 nickname으로 찾아올때도 같은 일을 하는 함수가 필요해서 By를 붙여 구분하였습니다. 
- `blocked?nickname=""` 구현
- 만든 함수들 이름이 좀 긴데 줄이기엔 애매해서 그냥 놔두었습니다.
- close #78 
- close #79

:sparkles: [Feature] block-user API

---

backend/src/entity/friendship.entity.ts
backend/src/entity/message-view.entity.ts
backend/src/friend/dto/friend-response.dto.ts
backend/src/friend/dto/requested-friend-response.dto.ts
backend/src/friend/friend.controller.ts
backend/src/friend/friend.module.ts
backend/src/friend/friend.service.ts

- `GET /friend` API 구현
- `MessageView` 와 `Friendship` 간 순환참조를 해결하기 위해 `Relation<T>` 로 엔티티를 수정했습니다. [TypeORM 문서 참고](https://typeorm.io/faq#how-to-use-typeorm-in-esm-projects)
- 다른 entity 에서도 타입이 정의되지 않아서 어쩌구...  하는 순환참조 같아보이는 문제가 나면 이 해결방법이 도움이 될 것 같습니다.
- `-infinity` (`lastViewTime` 과 `lastMessageTime` 의 기본값) 이 select 했을 때 `null` 로 오길래 메세지 기록이 없어서 `lastMessageTime` 이 `-infinity` 이고 join 했을 때의 `messegeView` 가 없을 경우 `lastViewTime` 을 `null` 로 설정했습니다.
- close #83

✨ [Feature] get friend list API

---

backend/seeding/data-source.ts
backend/seeding/seeder/message.seeder.ts
backend/src/entity/message-view.entity.ts
backend/src/entity/message.entity.ts
backend/src/friend/friend.controller.ts
backend/src/friend/friend.module.ts
backend/src/friend/friend.service.ts
backend/src/user/user.module.ts

- `DELETE /friend/userId` 구현
- FriendService 메소드들에 주석 추가
-  `requestFriendByNickname` -> `requestFriendById` 호출하던 구조에서 중복 체크가 있어서 `requestFriend` 라는 공통 메소드를 만들고 `private` 으로 뺐습니다.
- friendship 이 삭제될 때 연결된 message 도 삭제되어야 하므로 `onDelete: cascade` 옵션을 `message.entity.ts` 에 추가했습니다.
- 근데 생각해보니 `messageView` 에도 있어야 할 옵션 같아서 적다가 추가했습니다.ㅎㅎ
- `getFriendship` 을 `findExistFriendRequest` 로 더 정확하게 명명했습니다. `accept: false` 인 레코드만 가져옵니다.
- 지난 pr 에서 `blockService` 에서 쓰는 `friendRepository` 부분을 `friendService` 로 빼달라고 하셨는데 friend 에서는 친구관계가 없을 때 에러를 던져버리고 block 에서는 없어도 아무일이 없어야해서 validation 로직까지 빼기가 좀 애매합니다...
`friendship` 을 find 하는 부분만 메소드가 되어버릴텐데 그러면 repository 를 직접 사용하는 것과 다른 점이 없는 것 같아 일단 놔뒀습니다.
- close #82

✨ [Feature] delete friend api

---

backend/src/auth/auth.module.ts
backend/src/blocked/blocked.controller.ts
backend/src/blocked/blocked.module.ts
backend/src/blocked/blocked.service.ts
backend/src/entity/user.entity.ts
backend/src/user/dto/nickname-request.dto.ts
backend/src/user/user.module.ts
backend/src/user/user.service.ts

차단한 유저를 해제하는 API 구현
- `/blocked/(user_id)` 구현
- 다른 레포지토리를 사용할 때 우선은 레포지토리는 본인(A) 도메인 레포지토리만 사용하고 남(B)의 레포지토리는  BService를 가져다가 사용하도록 했는데요. 이때 import 하는 범위를 현재는 Module로 하고 있습니다. 계속 module을 import 받아 BService를 사용하는 방식으로 진행할지 아니면 그냥 import 없이 BRepository를 가져다 쓸지는 각 방법의 장단점을 _**좀 더 공부해보고 위키 작성 후 리팩토링하도록 하겠습니다.**_    아무튼 현재는 모듈을 import 받고 BService(남의 서비스 클래스)를 가져다가 사용하는 방식으로 진행하겠습니다. 
- 두 모듈간의 순환 참조에 대해서도 우선 서버가 돌아가도록 두개 모두 forwardRef() 처리를 해놓고 자세한 이유는 _**더 공부해서 위키에 적도록 하겠습니다.**_ 
- createUser() in UserService에서 transaction 처리 해놨습니다. 
- close #106

✨ [Feature] delete block user API

---

backend/seeding/factory/message.factory.ts
backend/src/app.module.ts
backend/src/common/constant.ts
backend/src/entity/message.entity.ts
backend/src/friend/friend.module.ts
backend/src/message/dto/message-response.dto.ts
backend/src/message/message.controller.spec.ts
backend/src/message/message.controller.ts
backend/src/message/message.module.ts
backend/src/message/message.service.spec.ts
backend/src/message/message.service.ts

- `offset` 과 `friendID` 로 메세지를 32개씩 가져오는 `GET /message/friendId?offset=` api 구현
- message 를 가져올 때 불필요한 join 및 select 의 어려움으로 `Message` 엔티티를 변경했습니다. 자세한 변경점과 효과는 노션의 백엔드 위키에 [Join 이 필요없는 entity 의 property 분리](https://www.notion.so/Join-entity-property-dc6cd87ac9f24daabe31c07b24b2a2d7?pvs=4) 참고 바랍니다.
- entity 의 변경으로 seeding 파일에도 변경점이 있습니다.
- 변경된 entity 로 메세지를 32 개씩 가져오는 `getMessageList` 로직을 구현했습니다. `cursor` 가 오지 않을 경우 `undefined` 인 점을 이용해서 아름답게 처리해보려고 했으나 global 로 설정된 `validationPipe` 덕분에 `number` 로 `transform` 되면서 `NaN`이 되어버려.. 그냥 `isNaN` 을 사용해서 처리해줬습니다.
- close #22

✨ [Feature] get messages API

---

backend/seeding/data-source.ts
backend/seeding/reset-db.sh

- yarn seed:reset 시 env 파일에 대응하도록 수정
- `dropdb` 와 `createdb` 대신 `psql -c` 로 직접 쿼리실행
- 도커에서 사용할 경우를 위해 host, port, user 지정해서 사용하도록 변경. 
- close #134

🐛  [BugFix] Fix seeding for all host and port

---

backend/src/auth/auth.service.ts
backend/src/blocked/blocked.controller.ts
backend/src/blocked/blocked.module.ts
backend/src/blocked/blocked.service.ts
backend/src/entity/friendship.entity.ts
backend/src/friend/dto/friend-response.dto.ts
backend/src/friend/friend.controller.ts
backend/src/friend/friend.module.ts
backend/src/friend/friend.service.ts
backend/src/user/user.service.ts

- 친구 리스트 get 하는 api 명세 변경
- 친구와 차단 api 에 부족했던 관계 로직 추가.
- 차단시 친구, 쌍방 친구신청 row 제거
- 친구 신청 전 block 여부 check
- 친구 리스트 get 하는 api 에 message id 추가 및 객체 변경
- api 가 바뀜에 따라 `FriendResponseDto` 도 변경되었습니다.
- transaction 이용하여 친구, 친구 신청을 모두 삭제하는 로직 추가
- friendship entity 변경
- sender => senderId, sender
- receiver => receiverId, receiver
- 친구 신청시 차단관계면 불가능하도록 처리
- friend 에서 block 사용 부분을 `BlockedService` -> `BlockedUserrepository` 를 사용하도록 변경
- `FriendService` 메소드 순서를 `private` 이 밑으로 가게 변경
- `AuthService` 에 있던 리팩토링으로 안쓰게 된 `changeAuthStatus` 메소드 제거
- `BlockedService` 의 에러 시 상태코드 일부 변경 (`Conflict` -> `BadRequest`)
- close #105 
- close #125

✨ [Feature] enhancing friend and blocked API

---

backend/.eslintrc.js
backend/src/blocked/blocked.controller.ts
backend/src/blocked/blocked.service.ts
backend/src/blocked/dto/response/blocked-user-response.dto.ts
backend/src/friend/friend.controller.ts
backend/src/friend/friend.service.ts
backend/src/message/message.controller.ts
backend/src/message/message.service.ts
backend/src/user/dto/request/user-image-request.dto.ts
backend/src/user/dto/request/user-nickname-request.dto.ts
backend/src/user/user.controller.ts
backend/src/user/user.service.ts

- eslint-plugin-import setting 변경
- `'import/external-module-folders': ['../types']` 를 삭제하여 기존 external module 이 인식되지 않는 문제 수정
- `@/types/**` 를 `internal` 로 설정해서 기존 상대경로 `import` 문보다 위에 정의
- close #153

:bug: [BugFix] Fix eslint plugin import groups

---

backend/.eslintrc.js
backend/src/blocked/blocked.controller.ts
backend/src/blocked/blocked.service.ts
backend/src/common/dto/success-response.dto.ts
backend/src/common/pipe/nickname-to-id.pipe.spec.ts
backend/src/common/pipe/nickname-to-id.pipe.ts
backend/src/friend/friend.controller.ts
backend/src/friend/friend.service.ts
backend/src/user/dto/request/user-nickname-request.dto.ts

- nickname 을 user id 로 바꾸는 `NicknameToIdPipe` 구현
- 유저 차단, 친구 신청 시 받는 query string 의 `nickname` 을 검증하는 pipe 를 구현했습니다. 정규식과 `class-validator` 의 `match()` 를 사용해서 검사합니다. `false` 일 경우 `BadRequestException` 을 throw 합니다.
- pipe 를 test 하는 spec 파일을 생성했습니다.
- 테스트 결과
- 테스트 파일에서 `as any` 를 자주 사용하는데 `eslint` 로 검사할 필요가 없다고 판단해서`*.spec.ts` 파일은 무시하도록 했습니다. 
- 기존 로직을 pipe 를 사용하는 방향으로 변경하고 공통되는 함수를 합쳐서 리팩토링 했습니다.
- 현재 nickname + userId 로직이 합쳐지면서 닉네임을 사용하는 api 에서는 유효한 user 인지 검사를 두 번 하게 되는데 추후 `userId` 만 검증하는 pipe 로 분리하기 위해 `NOTE` anchor 로 표시해놨으니 참고바랍니다.
- close #161

✨ [Feature] Add nickname to id pipe 

---

backend/src/blocked/blocked.controller.ts
backend/src/blocked/blocked.module.ts
backend/src/blocked/blocked.service.ts
backend/src/common/pipe/check-user-id.pipe.spec.ts
backend/src/common/pipe/check-user-id.pipe.ts
backend/src/common/pipe/nickname-to-id.pipe.spec.ts
backend/src/common/pipe/nickname-to-id.pipe.ts
backend/src/friend/friend.controller.ts
backend/src/friend/friend.module.ts
backend/src/friend/friend.service.ts
backend/src/main.ts
backend/src/message/message.controller.ts
backend/src/user/user.controller.ts
backend/src/user/user.service.ts

- 해당하는 유저가 없으면 404 에러를 보내는 `CheckUserIdPipe` 구현
- 내장 `ValidtaionPipe` 에서 보내던 error message 형태를 `string` 으로 변경
- `ValidationPipe` 의 `transform: true` 삭제
- `NicknameToIdPipe` 에서 `UserService` 를 사용하던 부분을 `Repository<User>` 로 변경
- user 가 없으면 404 에러를 보내는 `CheckUserIdPipe` 구현
- 기존 `findExistUserById` 를 사용하던 부분에 `CheckUserIdPipe` 를 적용했습니다.
- pipe 로 분리된 메소드를 `UserService` 에서 삭제
- `findExistUserById`, `findExistUserByNickname` 을 삭제했습니다.
- pipe 에서 service 를 사용하는 방법도 있었는데, controller 이전에 처리될 것이기 때문에 더 안쪽에 있는 service layer 를 사용하는 것은 적절치 않다고 판단했습니다.
- 사용되지 않는 `UserModule`, `UserService` import 삭제
- 기존 다른 service 에서 참조되는 관계를 삭제하면서 import 문들도 삭제되었습니다.
- `NicknameToIdPipe` 테스트 결과 전역으로 적용된 `ValidtaionPipe({transform: true})` 에 의해 `nickname` 이 해당 파이프에 들어오기 전에 먼저 `number` 로 변환되어 버려서 `transform: true` 옵션을 …

✨ [Feature] Add check user id pipe

---

frontend/src/layout/Grid/Grid.tsx

grid component에서 row와 column을 지정해주어도 colxcol기준으로 grid가 만들어지는 error를 고쳤습니다.

🐛 [Fix] Grid component's grid-template-rows

---

backend/.env.example
backend/src/config/app/configuration.module.ts
backend/src/config/app/configuration.service.ts
backend/src/config/app/configuration.ts
backend/src/main.ts

- client app 에 cors 허용해주는 미들웨어 설정
- `backend/env.example` 에 `CLIENT_APP` 이 추가되었습니다. `.env` 작성하실 때 client app 의 host 를 작성해주시면 됩니다.
-  nest app 의 `enableCors()` 로 `express` 의 [`cors`](https://github.com/expressjs/cors#configuring-cors-asynchronously) 패키지를 사용해서 설정할 수 있습니다. `app` 에서 `enableCors()` 해주면 모든 요청에 적용됩니다.
- `origin`: `Access-Control-Allow-Origin` 헤더를 설정합니다. env 의 `CLIENT_APP` 이 값으로 들어갑니다.
- `credentials` : `Access-Control-Allow-Credentials` 헤더를 설정합니다. 쿠키와 `Authorization` 헤더 사용을 위해 필요합니다.
- `allowedHeaders`: `Access-Control-Allow-Headers` 헤더를 설정합니다.  다른 origin 에서 온 `request` 헤더 중 허용할 헤더를 설정합니다. `Authorization` 과 `x-my-id` 가 사용되므로 설정했습니다.
- `exposedHeaders`: `Access-Control-Expose-Headers` 헤더를 설정합니다. `Location` 을 응답으로 줄 때가 있으므로 설정했습니다.
mdn 에 각 헤더별 설명이 잘 되어있으니 읽어 보시는 것을 강력 추천합니다!!
설정 후 …

🐛 [BugFix] Set server enbaleCors

---

backend/seeding/factory/frieindship.factory.ts
backend/seeding/factory/message.factory.ts
backend/seeding/seeder/message.seeder.ts
backend/src/entity/friendship.entity.ts
backend/src/friend/dto/response/friend-response.dto.ts
backend/src/friend/friend.service.ts
backend/src/message/dto/response/message-response.dto.ts
backend/src/user/dto/response/user-history-response.dto.ts
database/create-table.sql
types/friend/response/friend-response.interface.ts
types/message/response/message-response.interface.ts
types/user/response/user-history-response.interface.ts

- user 1, 2, 3 을 고정적으로 생성하도록 seed 코드 수정
- dto 타입의 `Date` 를 `Date|string` 으로 변경
- messege -> message 로 오타 수정
변경된 seed 데이터 사항은 다음과 같습니다.
- 유저 id 1, 2, 3 은 무조건 `REGISTERED` 로 존재 (user table 에 존재)
- friend id 1 은 무조건 존재하며, 1과 2의 친구 관계를 나타냄
- friend id 1 의 메세지 기록은 무조건 존재
- friend id 2 는 무조건 존재하며, 1이 3에게 친구 신청한 관계
- 불규칙하게 생성되던 메세지 데이터를 시간순으로 순차 생성되도록 변경.
- close #177

:sparkles: [Feature] Add fixed seeding data

---

backend/src/app.module.ts
backend/src/auth/auth.controller.ts
backend/src/auth/auth.module.ts
backend/src/auth/auth.service.ts
backend/src/auth/decorator/extract-user.decorator.ts
backend/src/auth/decorator/skip-user-guard.decorator.ts
backend/src/auth/guard/ft.guard.ts
backend/src/auth/guard/guest.guard.ts
backend/src/auth/guard/user.guard.ts
backend/src/auth/strategy/ft.strategy.ts
backend/src/auth/strategy/guest.strategy.ts
backend/src/blocked/blocked.controller.ts
backend/src/common/decorator/extract-user-id.decorator.ts
backend/src/friend/friend.controller.ts
backend/src/main.ts
backend/src/message/message.controller.ts
backend/src/user/user.controller.ts
backend/src/user/user.module.ts
backend/src/user/user.service.ts

- 로그인 관련한 Guard 적용
- 기존 AuthGuard 수정
- `AuthGuard('ft')` -> `FtGuard`
- `AuthGuard('user')` -> `UserGuard`
- `AuthGuard('auth')` -> `GuestGuard`
- `UserGuard` 전역 가드로 적용
- development 단계에서 user guard 항상 true return
- UserGuard skip하는 `@SkipUserGuard` 생성
- `@Headers` 대신 `@ExtractUserId`로 수정
- 개발 단계에서 사용할 `x-my-id`는  `@ExtractUserId`에 내부적으로 추가함
- development 단계에서 token 없어도 테스트 가능한 것 확인 (header에 'x-my-id'로 테스트하기)
- #138

✨ [Feature] Apply Guards for user and guest

---

backend/src/auth/decorator/extract-user.decorator.ts
backend/src/user/user.service.ts

- 존재하는 유저에 대한 double check 삭제
- `ExtractUserId` decorator로 token에 담긴 userId를 사용하고 있음
- 이미 token으로 존재하는 유저임을 인증되었기 때문에 service 함수 내에서 중복 확인하는 로직 삭제
- #218

:hammer: [refactor] Delete double check for exist user

---

backend/package.json

- commit 시 husky 를 이용해 pre-commit 훅 걸어놓은 `lint-staged` 가 실행되지 않던 오류 해결
- package.json 에 있던 postinstall (`yarn` 이후 실행됨) 을 임의로 바꿔놓아서 문제가 생긴 듯 싶습니다. 원래대로 돌려놓았습니다........
- merge 후 `yarn` 을 한 번만 실행해주시면 `husky install` 이 다시 실행되면서 해결됩니다. 안되면 다시 문의주십쇼!!

:bug: [BugFix] Fix pre-commit hook not running error

---

backend/package.json
backend/src/app.module.ts
backend/src/friend/dto/response/friend-response.dto.ts
backend/src/friend/friend.module.ts
backend/src/friend/friend.service.ts
backend/src/repository/chat.repository.ts
backend/src/repository/repository.module.ts
backend/src/repository/user-status.repository.ts
backend/yarn.lock
types/friend/response/friend-response.interface.ts

- 친구의 접속 상태 표시를 위해 `GET /friend` API 수정
- `RepositoryModule` 을 `AppModule` 에 등록 및 `FriendModule` 에서 import 하여 사용합니다.
- `ts-node` 로 컴파일하면 패키지 로딩 때 `require` 가 사용되는데, `nanoid@4.0.0` 부터는 `import` 만 허용되고 `require` 는 허용하지 않는 이슈가 있어 `3.4.4` 로 버전을 다운그레이드 하였습니다. [참고](https://github.com/ai/nanoid/issues/365)
- close #226

✨ [Feature] Add status to get friends

---

backend/.env.example
backend/src/common/option/cors.option.ts
backend/src/main.ts
backend/src/user/user.gateway.ts

- websocket cors 설정 추가
- `development` 일 때 socket 에서 `x-my-id` 헤더 사용하도록 설정
- cors option 파일을 분리해서 `WebSocketGateway` 와 `enableCors()` 에서 모두 사용합니다.
- `development` 면 `x-my-id` 에서 id 를 가져와 세팅합니다.
- 변수명을 `socketRepository` -> `socketIdRepository` 로 변경했습니다.
- http exception 을 `throw` 하던 부분을 `disconnect()` 후 `return` 으로 변경했습니다. 
- close #243 #244

✨ [Feature] Websocket environment setting

---

backend/src/entity/user.entity.ts
backend/src/friend/friend.gateway.spec.ts
backend/src/friend/friend.gateway.ts
backend/src/friend/friend.module.ts
backend/src/friend/friend.service.ts
backend/src/message/message.gateway.ts
backend/src/user/dto/response/user-profile-response.dto.ts
backend/src/user/dto/user-info.dto.ts
backend/src/user/user.gateway.ts
types/user/response/user-profile-response.interface.ts
types/user/user-info.interface.ts

- 친구 신청 수락 시 상대방 (receiver) 에게 sender 의 정보를 emit (get friend API 와 동일한 형식의 객체) 하는 `friend-accepted` 구현
- `join-message-room` 을`join-friend-room` 으로 변경 후 파일 이동
- `leave-friend-room` 구현
- 이벤트 명을 message room -> friend room 으로 바꾸면서 module 이 `message`-> `friend` 로 변경되었습니다.
- friend service 에서 join 하던 코드를 삭제했습니다. `join-friend-room` 이벤트로 대체됩니다.
- 기존에 `socketId` 로 `socket` 객체를 찾아서 `join()`, `emit()` 하던 것을 `socketId` 로도 할 수 있다는 것을 깨닫고 대체하였습니다.....
- nullable 한 entity의 column 타입들에 `null` 을 추가하여 union type 으로 만들었습니다.
- close #275 
- close #278

✨ [Feature] Friend accept event

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.module.ts
backend/src/auth/auth.service.ts
backend/src/auth/decorator/extract-user.decorator.ts
backend/src/auth/dto/request/code-verification-request.dto.ts
backend/src/auth/strategy/ft.strategy.ts
backend/src/auth/type/login-info.ts
backend/src/auth/type/two-factor-auth.ts
backend/src/entity/auth.entity.ts
types/auth/request/code-verification-request.interface.ts
types/auth/request/index.ts

- 2단계 인증 코드 검증하는 API
- 기존 `LoginInfoDto`를 `LoginInfo`로 수정하고 `auth/type/`으로 옮겼습니다.
- `auth/type`에 Cache에서 value로 사용할 type `TwoFactorAuth` 추가했습니다.
- 이미 2단계 인증 완료한 유저인지 확인
- `Cache에` 있는지 확인 (유효한 인증코드인지 확인)
- 중복된 이메일인지 확인
- `Cache에` 있는 코드와 일치하는지 확인
- `auth`의 `twoFa` column 업데이트
- `Cache`에서 삭제
- #209

✨ [Feature] Two Factor Authenticaion verification API

---

backend/seeding/factory/auth.factory.ts
backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts

- 2fa 이메일 삭제 API
- `twoFa` column이 nullable 하지만 삭제할 때 `null`로 저장이 불가능.. 그래서 `''` 로 값 update
- 자세한 내용은 [여기](https://www.notion.so/62e181f2f7904be9bbd95c9996f40f5b?v=f0730e2561194222b354c04a1f83abee&p=91cd36f9f16c4015a20d3333bd3dedb7&pm=s)를 참고해주세요
- 라고 했으나 해결법을 알려주셔서 null로 저장합니다!
- #230

✨ [Feature] Add 2fa delete API

---

backend/src/user/dto/response/user-nickname-response.dto.ts
backend/src/user/user.controller.ts
backend/src/user/user.service.ts
types/user/response/index.ts
types/user/response/user-nickname-response.interface.ts

- nickname 변경 api의 response 수정
- nickname response dto 삭제
- `updateUserNickname` return type `Promis<SuccessResponseDto>`로 변경
- #306

:bug: [Fix] Modify nickname response to SuccessResponseDto

---

backend/src/friend/friend.gateway.ts
backend/src/message/dto/socket/message.dto.ts
backend/src/message/message.gateway.ts
types/message/socket/message.interface.ts

- `createdAt`, `receiverId`를 `messageDto` 및 message `type`에 추가했습니다.
- `receiverId`를 이용해서 socketId로 보내는 로직 구성했습니다.
- dto로 받은 `createdAt`으로 message entity를 db에 저장합니다.
- `createdAt` : 페이지 구성할 때 필요하다는 요청 발생하여 추가했습니다. 
- `receiverId` : 클라이언트에서 보내줄 수 있고 해당 값이 있으면 서버에서 socket room을 만들지 않아도 됨, room으로 인해 생겼던 event 삭제 가능해서 반영했습니다. 
- 친구 관계로 socket room을 만들어 메세지를 보내는 로직이 삭제되면서 dto의 친구 관계 아이디의 유효성을 검사해야하나 고민했는데요.
`friendId`의 유효성을 검사한다면 고려해야할 점이 2가지 있다고 생각했습니다. 
1. blocked 되어서 메세지 씹혀야 하는 경우
2. 그냥 유효하지 않은 친구인 경우 
`1`에 대해서는 프론트에서 blocked 리스트 가지고 있어서 그냥 이벤트 받아서 잘 처리해주기로 해서 고려하지 않아도 됩니다.  
그럼 `2`가 남는데 소켓 통신이니까 빠르게 동작하는 걸 멈출만큼 필요한가 를 중점으로 생각했습니다. db를 다녀오려면 `await`를 거니까요. 그런데 어차피 이 이벤트를 발생할 때는 프론트에서 메세지 페이지에서 가지고 있는 친구데이터로 `friendId`를 넣어서 event 보내게 됩니다. 즉, 정상적인 `ui`로 동작시켰다면 일어나지 않을 일인거죠! 유효하지않은 값을 넣어서 보내려면 …

:hammer: [Refactor] Add createdAt, receiverId in messageDto 

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/auth/guard/two-fa.guard.ts
backend/src/common/constant.ts

- 2fa 설정한 유저에 대한 로그인 로직 추가
- 2fa 검증이 '초기 설정', '로그인' 두 가지 경우에서 발생하는데 로직이 다릅니다!
- 두 로직 모두 내부적으로 `verifyTwoFactorAuth` private 함수 호출하여 2fa 인증코드를 검증
- **'2fa 초기 설정'** 과정에서 code 검증 : `auth` table의 `two_fa` column 업데이트
- `POST /auth/2fa/verify` -> `updateTwoFactorAuth`
- **'2fa 로그인'** 과정에서 code 검증 : `user` access token 발급 후 `${clientUrl}/auth?token=`으로 redirect
- `POST /auth/42login/2fa` -> `TwoFactorAuthSignIn`
- 2fa 인증번호 생성 및 이메일 전송하는 함수 분리 : `sendAuthCode`
- 2fa 인증번호 검증하는 private 함수 분리 : `verifyTwoFactorAuth`
- `GET /auth/42login/callback`
- 2fa 이메일 존재할 경우 `sendAuthCode`로 인증번호 이메일 전송 -> 'jwt-for-2fa' token cookie 설정
- `POST /auth/42login/2fa`
- 로그인 2단계 인증 검증 및 user token 발급 후 redirect
- #231

✨ [Feature] Two factor authentication on Login

---

backend/src/channel/channel.controller.ts
backend/src/channel/channel.service.spec.ts
backend/src/channel/channel.service.ts
backend/src/channel/dto/decorator/is-password-required.decorator.ts
backend/src/channel/dto/request/join-channel-request.dto.ts
backend/src/channel/type/channel-mode.type.ts
backend/src/common/constant.ts
backend/src/common/pipe/check-channel-id.pipe.ts
types/channel/request/index.ts
types/channel/request/join-channel-request.interface.ts

- 채널 참여하기 http API
- `JoinChannelRequestDto` 생성
- `CheckChannelIdPipe` pipe 생성 
- param으로 들어온 `channelId`가 `channelRepository`에 존재하는 지 확인 후 `Channel` 객체로 변환
- `@IsChannelPassword` decorator에서 사용할 `ChannelPassword` `type` 추가
- #317

✨ [Feature] Add join channel API

---

backend/src/channel/dto/socket/chat.dto.ts
backend/src/entity/game-history.entity.ts
backend/src/game/dto/game-start.dto.ts
backend/src/game/dto/move-bar.dto.ts
backend/src/game/dto/request/create-game-request.dto.ts
backend/src/game/game-engine.service.ts
backend/src/game/game.controller.ts
backend/src/game/game.engine.ts
backend/src/game/game.gateway.ts
backend/src/game/game.module.ts
backend/src/game/game.service.spec.ts
backend/src/game/game.service.ts
backend/src/message/dto/socket/last-message-view.dto.ts
backend/src/message/dto/socket/message.dto.ts
backend/src/repository/game.repository.ts
backend/src/repository/model/game.ts
backend/src/user/user.service.ts
game/utils.ts
types/game/bar-moved.interface.ts
types/game/game-end.interface.ts
types/game/game-start.interface.ts
types/game/index.ts
types/game/move-bar.interface.ts
types/game/request/create-game-request.interface.ts
types/game/request/index.ts

- 게임 시작 후 본격적인 게임 로직 실행과 클라이언트 웹소켓 처리 로직
- 서버에서 10ms 마다 실행되는 게임엔진 update
- 500ms 마다 실행되는 synchronize 를 위한 websocket event `game-data` emit
- `GameData` 와 엔진 실행 시 필요한 메타데이터를 포함한 model 을 생성했습니다.
- 10ms 마다 실행한 `setInterval` 의 리턴값을 `engineIntervalId`, 500ms 마다 실행한 `setInterva` 의 리턴값을 `syncIntervalId` 로 저장합니다.
- 모든 player 가 `game-start` 를 회신했는 지 확인하는 `playerStarted` 배열을 기본값 `[false, false]` 로 저장합니다.
- 10ms 마다 공을 움직이면서 벽과 player 의 bar 에 닿았는지 체크합니다. 닿았다면 `game-data` 이벤트를 `emit` 합니다.
- `checkWallCollision()` 은 클라이언트 측에서도 체크하고, 똑같은 방향으로 전환될 것이기 때문에 `game-data` 를 보내지 않고 계산만 합니다.
- 10점을 달성했을 경우 `endGame()` 을 실행해서 게임 종료 시 이루어져야 할 `User`, `UserHistory`, `UserRecord` 의 업데이트 및 Repository 들을 업데이트 하는 로직을 실행합니다다.
- 저장된 id 들을 이용해 `claerInterval()` 로 루프를 종료합니다.
- `move-bar`
- 플레이어가 bar를 움직이는 이벤트가 일어난 경우로 …

✨ [Feature] Game server side engine and events

---

backend/src/channel/channel.gateway.ts
backend/src/channel/dto/socket/operation.dto.ts
types/channel/socket/index.ts
types/channel/socket/operation.interface.ts

- `kick` 하는 이벤트 추가했습니다. 
- `kick` 했을 때의 로직은  다음과 같습니다. 
1. 존재하는 채널인지 확인한다.
2. 유저가 채널에 존재하는 사람인지, 킥 권한이 있는 사람인지 확인한다. 
3. 타겟이 채널에 존재하는 사람인지, 누구에게도 킥 당할 수 없는 사람은 아닌지 확인한다. (오너, 게임중)
4. 유저가 타겟을 킥할 수 있는 지 확인한다.
5. 유저를 방에서 내보내는 서버 내부 로직 구현
1. `channel.users`에서 삭제한다. 
2. `mute 중` 이면 `캐시`에서 삭제한다. 
6. kick 당한 유저 포함, 채널 내 다른 유저들에게  `kicked` 이벤트를 보낸다.
7. `소켓 room`에서 삭제한다. 
- 유저와 타겟유저의 유효성을 확인하는 로직이 `kick`, `ban`, `mute` 가 모두 똑같아서 모든 `Operation`에 대해서 확인받고 나면 공통함수로 빼보도록 하겠습니다. 
- Operation `kick`, `ban`, `mute` 모두 클라이언트에서 오는 dto가 동일하여 OperationDto로 이름짓고 공통으로 사용하려고 합니다. 
- close #377

✨ [Feature] Feature socket-kick event

---

backend/src/channel/channel.controller.ts
backend/src/channel/channel.gateway.ts
backend/src/channel/channel.service.spec.ts
backend/src/channel/channel.service.ts

- 플레이어로 참여하기 로직 추가
- `PATCH /channel/:channelId/player`로 요청 발생 -> 성공적으로 참여 -> `player` socket event로 broadcast
- close #365

✨ [Feature] Participate as player

---

backend/src/game/dto/player-ready.ts
backend/src/game/game.controller.ts
backend/src/game/game.gateway.ts
backend/src/game/game.service.ts
types/game/game-end.interface.ts
types/game/game-start.interface.ts
types/game/index.ts
types/game/player-ready.interface.ts

- game start  POST 요청 시 channel 을 못찾던 문제 수정
- `game-start` event 타입 수정
- `gameService` 에서 `injection` 받던 객체를 `ChannelRepository`-> `InvisibleChannelRepository`, `VisibleChannelRepository` 로 변경했습니다.
- `start-game` (client -> server) 의 이름이 `player-ready` 로 변경되고 타입 이름도 변경되었습니다.
- `start-game` (server -> client) 의 emit data type 이  left, right player 의 `MemberInfo`를 포함하도록 수정되었습니다.
- close #404 
- close #402

✨ [Feature] Modify game start event data type

---

backend/src/channel/channel.gateway.ts
backend/src/channel/channel.module.ts
backend/src/connection/connection.gateway.ts

- 기존 channel gateway에 있던 `leaveChannel` 함수를 공통으로 사용하기 위해 함수 분리
- connection gateway `disconnect`, channel에서 `kick`, `ban`에서도 채널을 나가는 함수가 필요함
- connection gateway에 leaveChannel 함수 생성
- `socket` 파라미터 대신 `SocketIdRepository`에서 `socket` find해서 `user-left-channel` event emit하는 방법도 있는데 어차피 socket 객체를 가지고 있어서 socket으로 넘겼습니다
- close #384 
- close #400

:hammer: [Refactor] Move leave channel function to connection gateway

---

backend/src/auth/guard/ft.guard.ts
backend/src/auth/guard/user.guard.ts
backend/src/auth/strategy/ft.strategy.ts
backend/src/user/user.service.ts

- 로그인 관련된 에러사항 수정
- 가끔씩 발생하는 42 profile 가져오지 않는 문제를.. 일단 retry 하는 방식으로 만들어뒀습니다.
- `passport-42`를 이후에 사용하지 않는 걸로 리팩토링 해도 좋을 것 같다는 생각입니다 ㅎ.ㅎ (2019년 마지막 업뎃..)
- `user!`로 사용했던 부분 `null` 처리하는 방식으로 수정했습니다
- `SkipUserGuard`가 제대로 실행되고 있지 않아서 수정했습니다.
- `Logger` 추가
- close #432

🐛 [Hotfix] Fix login error

---

backend/src/achievement/achievement.module.ts
backend/src/achievement/achievement.service.ts
backend/src/app.module.ts
backend/src/friend/friend.module.ts
backend/src/friend/friend.service.ts

- 친구 관련 업적 구현했습니다. 
- 친구 요청을 수락할 때 진짜 친구가 되는데요. 이때 매번 sender와 receiver의 친구 수를 세는 함수 `checkFriendLimit`가 있어서 이 함수가 `count값`을 return 하도록 한 후 이 값을 사용해서 업적을 줄 수 있도록 했습니다. 
- 다만 친구요청을 정말 수락해서 `db`에 넣기 전에 친구 수를 세기 때문에 업적을 주는 함수 `getFriendAchievement`에 파라미터로 줄 때는 `+ 1` 해서  전달했습니다.
- 친구 수락과 업적 부여를 `trasaction`으로 묶었는데요. 업적 부여가 안된다고 해서 친구 요청 수락을 없던 일로 만드는게 맞을까?라는 생각을 했는데 그래도 친구 수 10명이 되었는데 (에러로 인해) 업적 부여가 안되었을 때 처리가 더 힘들어서 그냥 `trasaction`처리 했습니다. 만일 업적 부여 코드에서 에러가 발생했을 시에는 그냥 유저가 수락을 한번 더 하는 것도 페이지 상에서 이상하지 않다고 생각했습니다.
- #461

✨ [Feature] Achievement about friend

---

backend/src/achievement/achievement.module.ts
backend/src/achievement/achievement.service.ts
backend/src/friend/friend.service.ts
backend/src/game/game-engine.service.ts
backend/src/game/game.module.ts

- 게임 관련 업적 구현했습니다.
* 1 : 첫 승리                // 첫 승리 축하드립니다!!
* 2 : 승리 100회             // 승리 100회 달성!!
* 3 : 총 게임 횟수 42회      // 게임을 42!!
* 4 : 패배 횟수 42회         // 패배도 42!!
- `game-engine.service`의 `insertHistory`에서 업적 기록하고 난 후 `UserRecord`에 있는 레코드를 검색하여 `winCount` 와 `loseCount`를 통해 게임 기록 관련 업적을 부여합니다. 
- close #429

:sparkles: [Feature] Add achievement about game-history

---

backend/src/common/constant.ts

- cookie 옵션에서 secure 속성 제거
- cookie 옵션이 저장되어있던 `constants.ts` 에서 `secure: true` 속성을 제거했습니다.
- close #507

:bug: [BugFix] Fix cookie secure setting

---

frontend/src/pages/GameReadyPage/GameReadyPage.tsx

- 새로고침 event listener 제거
- 새로고침 event listener 제거
- 새로고침 버튼의 default 행동은 제어할 수 없어서, 게임 나감 처리를 하고 "접속 중인 유저가 아닙니다." alert 띄워주는 것으로 해결
- close #536

💚 [Chore] Delete refresh event listener

---

frontend/nginx.conf

- `nginx` config 파일에 socket.io proxy 추가
```
location /socket.io/ {
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $host;
proxy_pass http://ghostserver:3000;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
}
```
추가해주었습니다. 소켓 정상작동 됩니다. 
- #575

🐛 [BugFix] Add socket proxy

---

.github/workflows/docker-cd.yml
frontend/Dockerfile
frontend/src/pages/MessagePage/BlockModal/BlockModal.tsx
frontend/src/pages/MessagePage/FriendsModal/FriendsModal.tsx

- `uses: actions/checkout@v2:`
이 액션은 GitHub 저장소의 코드를 체크아웃합니다. 그래야만 워크플로우에서 이 코드에 접근할 수 있습니다.
- `uses: docker/setup-buildx-action@v1:`
Docker Buildx를 설치하고 초기화합니다. Buildx는 Docker의 CLI 플러그인으로, 멀티-플랫폼 이미지 빌드를 가능하게 합니다.
- `uses: docker/setup-qemu-action@v2:`
QEMU를 설치합니다. QEMU는 다양한 아키텍처에서 바이너리를 실행할 수 있도록 도와주는 에뮬레이터입니다. 이는 멀티-플랫폼 빌드에 유용합니다.
- `uses: docker/login-action@v1:`
DockerHub에 로그인합니다. 로그인에 사용되는 사용자 이름과 비밀번호는 GitHub Secrets에서 가져옵니다.
- `uses: docker/build-push-action@v4 (Backend & Frontend):`
Docker 이미지를 빌드하고 DockerHub에 푸시합니다. 이때 빌드에 사용되는 Dockerfile과 환경 변수 등이 지정됩니다. 또한, 빌드할 플랫폼도 지정합니다.
- `uses: appleboy/ssh-action@master:`
EC2 서버에 SSH로 접속하여 명령어를 실행합니다. 이 명령어들은 Docker 컨테이너를 관리합니다 (예: 이미지를 가져오기, 컨테이너 실행/정지 등).
- `runs-on: ubuntu-latest:` GitHub Actions 러너가 Ubuntu 환경에서 실행됩니다.
- `needs: …

:bug: [HotFix] Fix docker-cd.yml

---

backend/src/auth/auth.service.ts
backend/src/auth/strategy/ft.strategy.ts
backend/src/auth/strategy/google.strategy.ts
backend/src/auth/type/login-info.ts
backend/src/config/database/configuration.service.ts
backend/src/entity/auth.entity.ts

- email -> account id 로 구분하는 역할 (unique) 변경
- `auth.entity.ts` 가 변경 되었습니다.
- signin/signup 시 select 기준을 `email` 에서 `accountId` 로 변경했습니다.
- db 를 한 번 날릴 거라서 `synchronize: true` 옵션을 다시 켜줬습니다. 다음 pr 에서 없애는 걸로..ㅎㅎ
- strategy 들도 `id` 를 포함해서 가져오도록 변경되었습니다.
- close #620

🔨 [Refactor] Change to distinguish users by account ID

---

backend/src/auth/guard/user.guard.ts
docker-compose.local.yml
frontend/src/libs/api/client.ts
frontend/src/libs/api/socket.ts
package.json

- [[Chore] 로그인 구현완료로 인한 개발환경의 x-my-id 검증 로직 삭제](https://github.com/GhostPangPang/GhostPong/commit/5db6966fe27b8e9e503d7f758f1a0f98c8cdd468)
- [로컬 프로젝트 실행 스크립트파일 추가](https://github.com/GhostPangPang/GhostPong/commit/f85510ec68c2762a6bde99520602a4bea64290db)

💚 [Chore] 로그인 구현완료로 인한 개발환경의 x-my-id 검증 로직 삭제
