backend/nest-cli.json, backend/package.json, backend/src/main.ts, backend/yarn.lock
- `/api` 에 swagger document 세팅
- 간편한 DTO 감지를 위한 nest-cli swagger plugin 설정
- /api 로 접속 가능하도록 document setting.
- 컨트롤러 개발 시 nest 공식문서의 [Open API](https://docs.nestjs.com/openapi/operations) 부분 참고하면서 작성해주시면 됩니다.
- #14
=> 💚  [Chore] Add swagger settings

backend/.eslintrc.js, backend/.husky/pre-commit, backend/.prettierrc, backend/package.json, backend/src/app.controller.spec.ts, backend/src/app.controller.ts, backend/src/app.module.ts, backend/src/config/app/configuration.module.ts, backend/src/config/database/configuration.module.ts, backend/src/config/database/configuration.ts, backend/src/main.ts, backend/test/app.e2e-spec.ts, backend/yarn.lock
- eslint, prettier 세팅
- husky, lint-staged 로 commit 전 check
- nest.js 기본 세팅 + 간단한 import 정렬 순서만 추가
- [노션 위키](https://www.notion.so/eslint-import-rule-d38823e82f564609b4e63acc60dd3f37?pvs=4) 에 설정한 항목들을 추가해놨습니다.
- husky, lint-staged 는 프론트와 거의 똑같습니다. Thanks to @nyeoni ! 
- close #38
=> 💚 [Chore] eslint setting

backend/src/user/dto/update-image-request.dto.ts, backend/src/user/dto/user-info-response.dto.ts, backend/src/user/user.controller.ts, backend/src/user/user.service.ts, database/test-data.sql
유저의 프로필 이미지 변경하는 API 구현
- `user/image` api 구현
- repository의 find에 대해서 없는 데이터라는 에러를 처리할 때 개인적으로 return 값을 받아서 널 확인하는 방식을 좋아하는데요. 이렇게 되면 혹시나 find 실행시에 발생하는 다른 에러는 잡지 못할 수도 있나? 라는 생각이 드네요. 에러 처리에 대한 리뷰가 혹시 있으시면 가감없이 고고씽 해주십숑
- test-data.sql의 insert중 pk값에 대한 한나님의 조언을 받아 수정했습니다. 
- close #71
=> ✨ [Feature] update profile-image API

frontend/src/components/common/Avatar/Avatar.stories.tsx, frontend/src/components/common/Avatar/Avatar.tsx
GComponent에 맞게 Avatar Component 리펙토링
=> 🔨 [Refactor] avatar component

backend/src/blocked/blocked.controller.ts, backend/src/blocked/blocked.service.ts, backend/src/blocked/dto/blocked-list-response.dto.ts, backend/src/blocked/dto/blocked-user-response.dto.ts, backend/src/entity/blocked-user.entity.ts
차단한 유저 리스트 가져오는 API 구현
- `blocked`
- 내가 차단한 유저 리스트를 가져오는 API라서 별다른 에러가 떠오르지 않아 우선은 skip했습니다.
- close #107
=> :sparkles: [Feature] get blocked list API 

frontend/src/common/Text/Text.stories.tsx, frontend/src/common/Text/Text.test.tsx, frontend/src/common/Text/Text.tsx, frontend/src/common/Text/index.ts
- Text Component 구현
- Text Component Prop
```typescript
{
size?: FontSize;
color?: Color;
weight?: FontWeight;
children: string;
}
```
- #4
=> :sparkles: [Feature] text 컴포넌트

frontend/src/common/Avatar/Avatar.tsx, frontend/src/common/Dropbox/Dropbox.tsx, frontend/src/layout/Header/Header.tsx
avatar component size 수정 및 추가
dropbox 방향
- avatar size
sm : 2.4rem
md: 4rem
lg: 6.4rem
xl: 16rem
=> ✨ [Feature] avatar, dropbox 수정

frontend/src/assets/styles/theme.ts, frontend/src/common/Badge/Badge.stories.tsx, frontend/src/common/Badge/Badge.tsx
badge component의 status color를 theme color로 바꿈
=> 🔨 [Refactor] badge component theme color

frontend/src/assets/styles/theme.ts, frontend/src/common/Avatar/Avatar.tsx, frontend/src/common/ProgressBar/ProgressBar.tsx
=> 🔨 [Refactor] Add border option

backend/src/friend/dto/response/friend-response.dto.ts, backend/src/friend/friend.service.ts, backend/src/user/user.controller.ts, backend/src/user/user.service.ts, types/friend/response/friend-response.interface.ts
- 자잘한 수정사항 반영
- `GET /user` api에서 userId를 추가하여 response 하도록 고쳤습니다. 
- `GET /friend` api response dto `friendId` -> `id` 로 변경했습니다. 
- `UserController` 에서 메소드명에 `User`를 추가했습니다. 
- close #151 
- close #156
=> :hammer: [Refactor] Add userId in get-user-info API

backend/src/blocked/blocked.service.ts, backend/src/common/dto/error-response.dto.ts, backend/src/common/dto/success-response.dto.ts, backend/src/friend/friend.service.ts, backend/src/user/dto/response/user-nickname-response.dto.ts, backend/src/user/user.service.ts, types/common/response/error-response.interface.ts, types/common/response/index.ts, types/common/response/success-response.interface.ts
- dto 에 있던 constructor 를 삭제하고 `new` 를 이용해서 dto 생성하던 로직을 object literal 으로 변경.
- `types` 에 `common/` 의 dto 들을 인터페이스로 추가.
- close #140
=> 🔨 [Refactor] Remove contructors from dto

backend/src/message/message.controller.ts, backend/src/message/message.service.ts
- message get 할 때 에러 수정
- `sender.id` -> `senderId` , `receiver.id` -> `receiverId` 로 변경.
- `myId` 가 controller 에서 `string` 인데, service 의 매개변수로 넘어갈 때는 `string` -> `number` 로 타입변환이 안되므로 `+` 로 `service` 함수에서 `number` 로 변환도록 했습니다. `sender` 일 때도 `sender.id` 는 `number` 였을 텐데 그때는 왜 잘 되었을까요?....... 
- close #164
=> :bug: [BugFix] Fix friendship check in getMessagesList

frontend/src/common/Avatar/Avatar.tsx, frontend/src/common/ProgressBar/ProgressBar.tsx
=> 🔨 [Refactor] Avatar style

backend/src/auth/auth.service.ts, backend/src/blocked/blocked.controller.ts, backend/src/common/pipe/non-negative-int.pipe.spec.ts, backend/src/common/pipe/non-negative-int.pipe.ts, backend/src/friend/friend.controller.ts, backend/src/message/message.controller.ts, backend/src/message/message.service.ts, backend/src/user/user.controller.ts, backend/src/user/user.service.ts
- 음이 아닌 정수를 검증하는 `NonNegativeIntPipe` 적용
- 내장 파이프인 `parseInt` 를 상속받아 추가 검증을 하는 `NonNegativeIntegerPipe` 를 구현했습니다.
- 10진수형태의 양의 정수 (혹은 0) 인지 검증합니다. `2^31 - 1` 을 넘는 경우는 failure 입니다.
- close #169
=> ✨ [Feature] Add non negative int pipe

frontend/src/common/Button/index.ts, frontend/src/common/CommonButton/CommonButton.stories.tsx, frontend/src/common/CommonButton/CommonButton.tsx, frontend/src/common/CommonButton/index.ts, frontend/src/common/Dropbox/Dropbox.stories.tsx, frontend/src/common/GameButton/GameButton.stories.tsx, frontend/src/common/GameButton/GameButton.test.tsx, frontend/src/common/GameButton/GameButton.tsx, frontend/src/common/GameButton/index.ts, frontend/src/pages/LobbyPage/LobbyPage.tsx, frontend/src/pages/PrePage/PrePage.tsx
기존 Button을 GameButton으로 rename하고, 새로운 CommonButton 구현
=> ✨ [Feature] CommonButton implementation

backend/src/user/dto/response/user-history-response.dto.ts, backend/src/user/user.service.ts, types/user/response/user-history-response.interface.ts
- user history 총 갯수를 cursor=0 일 때 제공하도록 수정
- `total: number` 형태로 제공합니다.
- close #168
=> :sparkles: [Feature] Add total count to get user history API

frontend/src/assets/styles/theme.ts, frontend/src/layout/Content/Content.tsx, frontend/src/layout/Grid/Grid.tsx, frontend/src/layout/Header/Header.tsx, frontend/src/pages/LobbyPage/LobbyPage.tsx, frontend/src/pages/PrePage/PrePage.tsx
- Header, Content 의 style 변경
- Header 의 `height` 를 10rem 으로 고정
- Content 의 `height` 를 `calc(100% - 10rem)` 로 설정
- 그 외 모든 페이지의 `Wrapper` div 는 100% 로 설정해야함
- #201
=> 🔨 [Refactoring] layout style

frontend/src/common/Button/CommonButton/CommonButton.tsx
Add font color and change sizes
- button component에 글자색 옵션 추가
- 글자 bold채로 바꿈
- 사이즈 재 정의
=> 🔨 [Refactoring] Add font color and change sizes

frontend/src/assets/styles/theme.ts, frontend/src/common/InputBox/InputBox.stories.tsx, frontend/src/common/InputBox/InputBox.tsx, frontend/src/common/InputBox/index.ts
InputBox Component 만들었습니다.
`placeholder`
=> ✨ [Feature] InputBox implementation

frontend/src/common/Toggle/Toggle.stories.tsx, frontend/src/common/Toggle/Toggle.tsx, frontend/src/common/Toggle/index.ts
=> ✨ [Feature] Toggle implementation

backend/src/friend/friend.service.spec.ts, backend/src/repository/chat.repository.ts, backend/src/repository/model/user-status.ts, backend/src/repository/repository.interface.ts, backend/src/repository/user-status.repository.ts
- user 의 상태를 online, offline, game 으로 저장하는 `UserStatusRepository` 구현
- repository interface 의 제너릭이 헷갈려서 `<K, V>` 형태로 수정했습니다. 
- `ChatRepository` 의 `update` 에서 업데이트 이전의 객체를 리턴하는 문제를 수정했습니다.
- spec 파일의 컴파일 에러만 간단히 수정했는데 무시하셔도 됩니다.. 거슬려서 수정하였습니다..ㅎㅎ
- close #223
=> ✨ [Feature] User status repository

frontend/src/App.tsx, frontend/src/pages/EditProfilePage/EditProfilePage.tsx, frontend/src/pages/EditProfilePage/index.ts
=> ✨ [Feature] Add EditProfile Page

backend/src/common/option/cors.option.ts
- content-type 을 allowed header 에 추가
- `content-type: application/json` 도 허용해주기 위해 명시적으로 선언해줍니다.
- close #246
=> :bug: [BugFix] Add content type header to allow headers

backend/src/user/interceptor/file-upload.interceptor.ts, backend/src/user/user.controller.ts
- image upload 를 프로그램 변경사항에 맞춰 업데이트 및 버그 수정
- file naming 을 request.user 에 있는 userId 를 이용하도록 변경
- unsupported error 시 바로 return 되도록 처리
- close #253
=> :hammer: [Refactor] Modify image upload file naming

backend/public/asset/index.html, backend/src/friend/friend.module.ts, backend/src/friend/friend.service.ts, backend/src/message/dto/socket/leave-message-room.dto.ts, backend/src/message/dto/socket/message.dto.ts, backend/src/message/message.gateway.spec.ts, backend/src/message/message.gateway.ts, backend/src/message/message.module.ts, backend/src/user/user.module.ts, types/message/socket/index.ts, types/message/socket/leave-message-room.interface.ts, types/message/socket/message.interface.ts
메세지 창에서 메세지를 하기 위한 이벤트 구현했습니다. 
- 디버깅용 console.log가 많은데요. 프론트랑 맞춰보는 작업이 끝나면 다음 pr에 깔끔하게 삭제해놓겠습니다. 
- Error는 Error를 throw하도록 했습니다. 다음 task인 Error 설정을 처리하면서 함께 수정하겠습니다. 
- 다른 부분들은 코드에 직접적으로 설명하도록 하겠습니다. 
- close #238 
- close #240 
- close #241
- close #152
=> ✨ [Feature] socket event for message

backend/.env.example, backend/package.json, backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.ts, backend/src/auth/dto/request/two-factor-auth-request.dto.ts, backend/src/config/auth/mailer/configuration.module.ts, backend/src/config/auth/mailer/configuration.service.ts, backend/src/config/auth/mailer/configuration.ts, backend/src/user/dto/user-nickname-response.dto.ts, backend/yarn.lock, types/auth/request/index.ts, types/auth/request/two-factor-auth-request.interface.ts
- 2단계 인증 설정 시작하기 (인증코드 메일 발송)
- `Mailer` 라이브러리로 메일 전송
- 이때 필요한 보내는 사람의 email과 그 password는 `.env.example`에 추가했습니다
- 이 부분은 각자 `gmail` 이메일을 설정하고, 비밀번호는 '앱 비밀번호'를 발급 받아야 하는데 [여기](https://hyunmin1906.tistory.com/m/276) 그대로 따라하시면 됩니다!
- 인증 코드 6자리 랜덤 넘버로 생성
- email로 인증코드 전송
- cache에 추가
- `key`는 user id
- `value`는 { email, code }
- key를 email로 할 지 user id로 할 지 고민을 했는데요..! user id로 하게 된 이유는 [여기](https://www.notion.so/2-with-Mailer-6634f82ef1e44ea09bc9660b1f6ac80b)를 참고해주세요
- 위의 링크에 적혀있는 '1번 방법'과 '2번 방법' 중 '2번 방법'으로 진행한 건데 의견 있으시면 남겨주세요!
- 함께 얘기 나눈 결과 '2번 방법'(캐시 메모리 간 이메일 중복 검사 X)으로 확정되었습니다!
> 보통 이메일로 인증 단계에서 잘못된 이메일 혹은 다른 사람 이메일 등에 대한 검사가 없음 
인증 진행 과정에서는 해당 이메일에 대한 검사를 하지 않고 무조건 메일 발송함
위와 같은 상황을 고려해봤을 때 인증이 완료되지 않은, 인증 과정에서 캐시 메모리에 있는 이메일 중복 검사는 고려하지 않아도 된다고 판단!
- #228
=> ✨ [Feature] Two Factor Authentication setting

frontend/vite.config.ts
- `vite` 환경에 image proxy 설정
- `vite` 환경에 image proxy 설정
- #281
=> 🐛 [BugFix] Add image proxy

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/dto/response/two-factor-auth-response.dto.ts, types/auth/response/index.ts, types/auth/response/two-factor-auth-response.interface.ts
- 2fa 여부 가져오는 API
- `GET /auth/2fa`
- 2fa response dto 생성
- `auth`의 각 controller, service 함수 return type 추가했습니닷..ㅎㅎ
- #290
=> ✨ [Feature] Get two factor authentication API

frontend/src/common/Dropbox/Dropbox.tsx, frontend/src/pages/MessagePage/MessageList/MessageListItem.tsx, frontend/src/pages/ProfilePage/ProfilePage.tsx
=> 🐛 [Fix] Avatar pointer to dropbox

backend/src/entity/user.entity.ts, backend/src/user/dto/response/user-profile-response.dto.ts, backend/src/user/dto/user-info.dto.ts, types/user/response/user-profile-response.interface.ts, types/user/user-info.interface.ts
`string` | `null`이 에러나서 
`?: string`으로 수정했습니다
- close #297
=> :bug: [BugFix] Change image field types

frontend/src/libs/api/auth.ts, frontend/src/libs/api/client.ts
- sessionStorage 의 값으로 x-my-id 설정해주는 로직 추가
- message socket 통신 등 테스트를 위해 세션스토리지에 있는 값으로 가져오도록 구현
**- sessionStorage 에 `gpat` key 값에 `user_id` 를 넣어주시면 됩니다.**
- #300
=> :sparkles: [Feature] x-my-id sessionStorage getter

frontend/.eslintrc.json, frontend/index.html, frontend/src/App.tsx, frontend/src/assets/svgs/close.svg, frontend/src/common/Button/GameButton.tsx, frontend/src/common/Button/IconButton.stories.tsx, frontend/src/common/Button/IconButton.tsx, frontend/src/common/Button/index.ts, frontend/src/common/Modal/Modal.stories.tsx, frontend/src/common/Modal/Modal.tsx, frontend/src/common/Modal/ModalPortal.tsx, frontend/src/layout/Content/Content.tsx, frontend/src/pages/MessagePage/Message/MessageInput.tsx
- Modal 컴포넌트 구현
- React Portal 을 사용하여 Modal 구현
- IconButton 추가 
- eslint no-unused-vars 규칙 추가 -> 안쓰는 변수 방지
```typescript
children: React.ReactNode;
isOpen: boolean;
onClose: () => void;
```
- #233
=> ✨ [Feature] Modal component

frontend/src/hooks/useInput.tsx
Add useInput hook
자주 사용되는 use input hook을 만들었습니다
=> ✨ [Feature] Add useInput hook

backend/src/message/message.gateway.ts
- socket 통신시 dto에 대한 validation 후 던지는 예외를 WsException으로 던지도록 수정했습니다. 
- `Error`로 던지던 부분을 `WsException`을 던지도록 수정했습니다. 
- dto validation후 던지는 에러를 다음의 코드를 통해 WsException으로 변경하였습니다. 
```
@UsePipes(new ValidationPipe({ exceptionFactory: () => new WsException('Bad Request') }))
```
`exceptionFactory`는 validate를 통해 받은 에러를 `()`으로 받아서 `WsException`으로 해당 에러 정보를 출력합니다. 
- WsException()에 들어가는 message에 대해서 그동안 에러 메세지를 한글로 주고 있어서 http API를 확인했는데 그냥 bad request Exception을 던지는 것(에러 메세지-BadRequestException이 주는 영어 메세지)으로 해결하길래 `Bad request`라고 작성하였습니다. 
- close #294 
- close #295
뭐 되게 많을 줄 알고 이슈분리했는데 너무 별거 없어서 머슥하네요...
=> 🔨 [Refactor] Change error and http-bad-request to WsException

backend/src/connection/connection.gateway.ts
- web socket connect할 때 `auth`에 token 담는 것으로 수정
- 기존에는 `headers에` token 담음 -> `auth`로 수정했습니다.
- middleware에서 connect 처리를 하고 `connect_error` 이벤트를 보내고 싶어서 많은 시도를 해봤지만... 우선은 직접 `exception` event를 emit하는 것으로 만들었습니다
- 수정된 부분은 굉장히 굉장히 간단한데 하지만 그 과정은 매우 험난했습니다...
- connection에서 `guard`를 적용해보려고 시도했으나... 한참 시도했는데 안 되어서 알아보니 connection에서는 `guard`가 적용되지 않는 게 맞다고 합니다 (OMG)
[여기](https://github.com/nestjs/nest/issues/882)에 해당 내용에 대한 이슈가 있는데 궁금하신 분들은.. 보세요 ㅎㅎ
- 위의 과정들은 [여기](https://www.notion.so/websocket-connection-credential-postman-8dc8ef7db16e43eda5deeb4e76cbb5cb)에 있는데 .... 딱히 내용은 없고 그냥 삽질하면서 화났다는 글입니다 ༎ຶ‿༎ຶ
- #248 
- #296
=> :hammer: [Refactor] Modify location of token from headers to auth

backend/src/message/message.gateway.ts
- 에러메세지를 자세하게 client 에 보내기 위한 validation pipe 의 exception factory 수정
- bug 는 아니지만 hotfix 입니다 급하다급해
=> :bug: [Bugfix] Fix message gateway exception factory

backend/src/channel/dto/response/channels-list-response.dto.ts, types/channel/response/channels-list-response.interface.ts, types/channel/response/index.ts
- client 와 공유할 channel list dto 의 타입 추가
- ㅎㅎ.. 확인을 잘 하겠습니다.. 쏘리 승수쿤
=> ✨ [Feature] add types channel list

backend/src/user/dto/response/user-profile-response.dto.ts, backend/src/user/dto/user-info.dto.ts, backend/src/user/user.controller.ts, backend/src/user/user.service.ts, types/auth/index.ts, types/auth/request/index.ts, types/auth/response/index.ts, types/blocked/index.ts, types/blocked/response/index.ts, types/channel/index.ts, types/channel/request/index.ts, types/channel/response/channels-list-response.interface.ts, types/channel/response/index.ts, types/common/index.ts, types/common/response/index.ts, types/friend/index.ts, types/friend/response/friend-response.interface.ts, types/friend/response/index.ts, types/index.ts, types/message/index.ts, types/message/response/index.ts, types/message/socket/index.ts, types/user/index.ts, types/user/request/index.ts, types/user/response/index.ts, types/user/response/user-profile-response.interface.ts, types/user/socket/index.ts, types/user/socket/user-status.interface.ts, types/user/user-info.interface.ts
- `types` 에 불필요한 타입제거 및 import 를 위한 `index.ts` 생성
- `types` 에 `index.ts` 추가
- `UserStatus`-> `Status` 로 변경
- `UserInfo` 에 있던 optional type 삭제
=> 🔨 [Refactor] Refactoring types for client

backend/src/repository/game.repository.ts, backend/src/repository/model/game.ts
- 게임 레포지토리를 생성했습니다.
- 일정한 값으로 초기화 시켜주는 constructor 를 포함해서 `Game`, `GameRepository` 를 생성했습니다.
- close #339
=> :sparkles: [Feature] Add game repository

backend/src/channel/dto/response/channel-member-info-response.dto.ts, types/channel/response/channel-member-info-response.interface.ts
- `ChanelMemberInfoResponse` dto 오타 수정
- `observers`로 수정..ㅎㅎ
=> :bug: [Fix] Modify typo of channel memeber info response dto

backend/src/channel/channel.controller.ts, backend/src/channel/channel.service.spec.ts, backend/src/channel/channel.service.ts
- `GET /channel/:channelId`
- channel 정보 가져오는 API 
- close #344
=> ✨ [Feature] Get channel info API

backend/src/channel/channel.service.spec.ts, backend/src/channel/channel.service.ts, backend/src/channel/dto/response/full-channel-info-response.dto.ts, types/channel/response/full-channel-info-response.interface.ts
- `FullChannelInfo` dto 수정
- `name` 추가
=> :bug: [Fix] Add channel name to channel info dto

backend/src/channel/channel.controller.ts, backend/src/channel/channel.gateway.ts, backend/src/channel/channel.module.ts, backend/src/channel/channel.service.spec.ts, backend/src/channel/channel.service.ts
- 채널 초대하기 기능 추가
- 채널에 참여중인 유저가 친구인 유저를 초대하는 api 추가
- 초대 대상에게 `invite-channel` socket event emit
- close #318
=> ✨ [Feature] Add invite channel

backend/src/blocked/blocked.module.ts, backend/src/blocked/blocked.service.ts, backend/src/friend/friend.gateway.ts, backend/src/friend/friend.module.ts, backend/src/friend/friend.service.ts
- 친구 추가, 삭제될 때 socket 을 room 에서 추가, 삭제
- 친구 추가되면 `user-${userId}` 에 서로 추가하고 삭제되면 서로 삭제합니다.
- 차단될때도 친구가 삭제되므로 `removeFriendFromRoom` 해주었습니다.
- 해당 함수 사용을 위해 `blockedService` 에서 `friendshipGateway` 를 사용했습니다.
- close #374
=> ✨ [Feature] Manage room by friendship

game/utils.ts
- left player 의 충돌 영역이 조금 다른 문제 해결
- bar padding 을 더해서 계산하는 방향으로 변경
- close #383
=> :bug: [BugFix] Fix left player collision add padding

game/utils.ts
- bar padding 을 더하던 문제 수정
- bar width 를 더하도록 변경
=> :bug: [BugFix] Fix adding bar width

frontend/.eslintrc.json, frontend/src/App.tsx, frontend/src/assets/styles/theme.ts, frontend/src/constants/event.ts, frontend/src/hooks/index.ts, frontend/src/hooks/useCanvas.tsx, frontend/src/hooks/useChannel.tsx, frontend/src/libs/utils/canvas.ts, frontend/src/pages/GamePage/GamePage.tsx, frontend/src/pages/GamePage/PingPongGame.ts, frontend/src/pages/GamePage/index.ts, frontend/src/pages/GamePage/usePingPongGame.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/pages/GameReadyPage/Versus/Versus.tsx, frontend/src/pages/MessagePage/MessageList/MessageList.tsx, frontend/src/pages/MessagePage/MessagePage.tsx, frontend/src/stores/gameState.ts, frontend/tsconfig.json, frontend/vite.config.ts, game/game-data.ts, types/game/game-end.interface.ts
- Game view 페이지 구현
- canvas util 함수 추가
- useCanvas 추가
- close #347
=> ✨ [Feature] game view

frontend/src/hooks/useNewMessages.tsx, frontend/src/pages/MessagePage/Message/Message.tsx, frontend/src/pages/MessagePage/Message/MessageContent.tsx, frontend/src/pages/MessagePage/MessageList/MessageListItem.tsx, frontend/src/stores/messageState.ts
- message 창의 정렬 에러 수정
- useNewMessages 훅 수정
- messageState 수정
- close #389
=> 🐛 [BugFix] Fix message sort error

frontend/src/pages/ProfilePage/ProfilePage.tsx
=> 🐛 [BugFix] Fix Nan %

frontend/src/SocketHandler.tsx, frontend/src/hooks/channel/useChannel.tsx, frontend/src/hooks/channel/useChat.tsx, frontend/src/pages/GameReadyPage/ChatBox/ChatBox.tsx, frontend/src/pages/GameReadyPage/ChatBox/ChatInput.tsx, frontend/src/pages/GameReadyPage/ChatBox/Chatcontent.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/pages/GameReadyPage/ObserverBox/ObserverBox.tsx, frontend/src/pages/LobbyPage/LobbyPage.tsx, frontend/src/stores/channelState.ts
channel ready page chat socket connect
채널 레디 페이지의 채팅 소켓 연결 완료
- chat send
- chat recieve
Note: view 부분 수정 예정 : https://github.com/GhostPangPang/GhostPong/issues/409
=> ✨ [Feature] channel ready page chat socket connect

backend/src/channel/channel.controller.ts, backend/src/channel/channel.service.spec.ts, backend/src/channel/channel.service.ts
=> ✨ [Feature] Become owner

backend/src/channel/channel.controller.ts, frontend/src/SocketHandler.tsx, frontend/src/hooks/channel/useChannel.tsx, frontend/src/hooks/channel/useChat.tsx, frontend/src/pages/GameListPage/GameContent/GameContent.tsx, frontend/src/pages/GameListPage/GameHeader/GameHeader.tsx, frontend/src/pages/GameReadyPage/ChatBox/Chatcontent.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/pages/GameReadyPage/Versus/Versus.tsx, frontend/src/stores/channelState.ts, frontend/src/stores/gameState.ts
- 플레이어 참여하기 patch mutation 구현
- channel state 수정 및 리팩터
- useChannelInfo -> useChannel
- useChannel -> useChannelList 
- useChannelMutation 추가 -> patch pariticipate
- channelState 변수명 변경
- close #416
=> ✨ [Feature] channel participate

frontend/src/SocketHandler.tsx, frontend/src/hooks/channel/useChannel.tsx
Add PlayerEvent
https://github.com/GhostPangPang/GhostPong/issues/421
=> ✨ [Feature] Add PlayerEvent

frontend/src/SocketHandler.tsx, frontend/src/hooks/channel/useChannel.tsx, frontend/src/hooks/channel/useChat.tsx, frontend/src/libs/utils/itemgenerator.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/pages/GameReadyPage/ObserverBox/ObserverBox.tsx, frontend/src/pages/GameReadyPage/Versus/Versus.tsx
Channel be admin connect
- be admin http api
- be admin socket listen
- item generator for fitting dropbox
https://github.com/GhostPangPang/GhostPong/issues/423
channel id 안가는 이슈 고침
https://github.com/GhostPangPang/GhostPong/issues/428
=> ✨ [Feature] Channel be admin connect

frontend/src/SocketHandler.tsx, frontend/src/hooks/channel/useChat.tsx, frontend/src/libs/api/socket.ts, frontend/src/stores/channelState.ts, frontend/vite.config.ts
- `api/v1` 엔드포인트 대체
- http -> `/api/v1`
- socket -> base_url 그대로 
- #437
=> :hammer: [Refactor] Refactor api endpoint

frontend/src/SocketHandler.tsx, frontend/src/constants/event.ts, frontend/src/hooks/channel/useChat.tsx, frontend/src/pages/GameReadyPage/ChatBox/Chatcontent.tsx, frontend/src/stores/channelState.ts
Changed chat dto applying
https://github.com/GhostPangPang/GhostPong/issues/447
=> ✨[Feature] Changed chat dto applying

frontend/src/SocketHandler.tsx, frontend/src/hooks/channel/useChannel.tsx, frontend/src/libs/utils/itemgenerator.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/pages/GameReadyPage/Versus/Versus.tsx, frontend/src/stores/channelState.ts
Channel be owner connect
Note: https://github.com/GhostPangPang/GhostPong/issues/445 고쳐야함
=> ✨ [Feature] Channel be owner connect

frontend/src/SocketHandler.tsx, frontend/src/constants/event.ts, frontend/src/hooks/channel/useChannel.tsx, frontend/src/libs/utils/itemgenerator.tsx
Channel kick ban connect
- patch kick
- patch ban
- kick event listen
- ban event listen
https://github.com/GhostPangPang/GhostPong/issues/411
=> ✨[Feature] Channel kick ban connect

frontend/src/hooks/game/useGameMutation.tsx, frontend/src/hooks/game/useGameStart.tsx, frontend/src/hooks/useCanvas.tsx, frontend/src/pages/GamePage/GamePage.tsx, frontend/src/pages/GamePage/usePingPongGame.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/stores/gameState.ts
- `GameSocket` 연결
- 게임 `game-data` 소켓 연결
- 게임 `game-start` 소켓 연결
- 게임 `game-end` 소켓 연결
- 게임 `move-bar` 소켓 연결
- 게임 결과 페이지
- 그 외 Text, Avatar 컴포넌트 수정
- close #395
=> ✨ [Feature] Game socket

frontend/src/SocketHandler.tsx, frontend/src/hooks/channel/useChannel.tsx, frontend/src/hooks/channel/useChat.tsx, frontend/src/libs/api/socket.ts, frontend/src/libs/utils/itemgenerator.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/pages/GameReadyPage/RoomInfo/RoomInfo.tsx
Channel mute connect
- Mute api 연결
- chat ack message 띄워주기
https://github.com/GhostPangPang/GhostPong/issues/412
=> ✨ [Feature] Channel mute connect

frontend/src/hooks/user/useProfileData.tsx, frontend/src/pages/ProfilePage/ProfilePage.tsx
Profile Page userId Fix
- profile page에 userId에 맞게 값이 fetching이 안되는 부분 수정
https://github.com/GhostPangPang/GhostPong/issues/456
Note:  default 이미지는 undefined일때 잘 들어옵니다
=> 🐛 [BugFix] Profile Page userId Fix

frontend/src/pages/EditProfilePage/EditProfilePage.tsx
2Fa Email not showing all
인증된 이메일이 가려서 보이는 부분 해결
https://github.com/GhostPangPang/GhostPong/issues/457
=> 🐛 [BugFix] 2Fa Email not showing all

frontend/src/App.tsx, frontend/src/pages/GamePage/GamePage.tsx, frontend/src/pages/GamePage/GameResultModal/GameResultModal.tsx, frontend/src/pages/GamePage/usePingPongGame.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx
- Game mode 적용
- 게임 결과 모달 적용
- Game mode 적용
- 게임 결과 모달 적용
- close #449
=> ✨ [Feature] game mode

frontend/src/common/Dropdown/Dropdown.tsx, frontend/src/hooks/channel/useChannel.tsx, frontend/src/pages/GameReadyPage/RoomInfo/RoomInfo.tsx, frontend/src/pages/GameReadyPage/SettingModal/SettingModal.tsx
Channel info update dto
- mode update되는거 readypage업데이트
- dropdown value 도 받을 수 있도록 함
https://github.com/GhostPangPang/GhostPong/issues/468
=> ✨ [Feature] Channel info update dto

frontend/src/hooks/channel/useChannel.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx
Back button available 가능하게 하였음
- back button 가능하게 했음
- 채널 존재하지않을때 list로 리다이렉
https://github.com/GhostPangPang/GhostPong/issues/469
https://github.com/GhostPangPang/GhostPong/issues/475
=> 🔨 [Refactor] Back button available

backend/src/game/game-engine.service.ts
- channel 상태 업데이트가 안되던 오류 수정
- `VisibleChannelRepository`, `InVisibleChannelRepository` 모두에서 확인합니다.
=> :bug: [BugFix] Fix update isInGame state

backend/src/game/game.service.ts, frontend/src/App.tsx, frontend/src/hooks/game/useGameStart.tsx, frontend/src/hooks/useCanvas.tsx, frontend/src/layout/GameLayout/GameLayout.tsx, frontend/src/libs/utils/debounce.ts, frontend/src/libs/utils/sound.ts, frontend/src/pages/GameLoadingPage/GameLoadingPage.tsx, frontend/src/pages/GameLoadingPage/index.ts, frontend/src/pages/GamePage/GamePage.tsx, frontend/src/pages/GamePage/GameResultModal/GameResultModal.tsx, frontend/src/pages/GamePage/usePingPongGame.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/pages/LobbyPage/LobbyPage.tsx, frontend/src/stores/gameState.ts
- random game
- random game loading page
- random game
- random game loading page
- close #471
=> ✨ [Feature] random game

backend/src/channel/channel.service.ts, backend/src/user/dto/request/user-nickname-request.dto.ts, types/user/request/index.ts, types/user/request/user-nickname-request.interface.ts, types/user/user-nickname.interface.ts
- `channel-invited` event가 초대한 사람에게 emit 되고 있던 문제 해결
- `nickname`만 담은 `UserNicknameRequest` dto `UserNickname`로 수정
- 기존 `invite-channel` event 이름 `channel-invited`로 수정
- close #485
=> :bug: [BugFix] Fix channel-invited event target

frontend/src/pages/GamePage/GamePage.tsx
- Game 페이지 반응형 임시 처리
- 페이지 `width` 에 따라 % 로 설정되게 구현
- close #489
=> :sparkles: [Feaure] Update game responsive

backend/src/auth/auth.controller.ts, frontend/src/pages/TwoFactorLoginPage/TwoFactorLoginPage.tsx, types/auth/response/index.ts, types/auth/response/token-response.interface.ts
- 2fa 로그인 에러
- `SkipUserGuard` 적용 안 되고 있는 문제 해결 (Guard 적용 순서 영향..)
- 2fa 로그인 과정에서 redirect하면 CORS 문제 발생 -> body에 담아서 response
- token response dto 생성
- front에서 요청하는 2fa 로그인 api 수정
=> 🐛 [BugFix] Two Factor Auth login error

backend/src/auth/auth.controller.ts
- 2단계 인증 로그인에서 인증 완료 후 `jwt-for-2fa` 토큰 cookie에서 clear
- clearCookie로 쿠키 삭제
=> 🔨 [Refactor] Clear jwt-for-2fa cookie

frontend/src/App.tsx, frontend/src/ProtectedRoute.tsx, frontend/src/hooks/auth/useAuth.tsx, frontend/src/layout/Header/Header.tsx, frontend/vite.config.ts
- Socket 연결 에러
- static path 에러
- `vite.config.ts` 에 백엔드 정적 경로 수정
- `ProtectedRoute` 추가
=> 🐛 [BugFix] Static path error & Socket error

backend/src/auth/auth.module.ts, backend/src/auth/strategy/user.strategy.ts
- `UserGuard`에서 DB 확인 삭제
- `UserGuard`에서 DB 확인 삭제
=> :bug: [BugFix] Restore user guard

frontend/src/SocketHandler.tsx, frontend/src/constants/event.ts, frontend/src/hooks/blocked/useBlocked.tsx, frontend/src/hooks/friend/useFriend.tsx, frontend/src/pages/MessagePage/BlockModal/BlockModal.tsx, frontend/src/pages/MessagePage/FriendsModal/FriendsModal.tsx, frontend/src/types/query.ts
- 실시간 친구신청 및 차단 수정
- 친구 수락 이벤트 처리
- 실시간 친구신청 및 차단 수정
- 친구 수락 이벤트 처리
- close #509
=> 🐛 [BugFix] Refactor messagePage live api error

frontend/src/common/Text/Text.tsx, frontend/src/pages/MessagePage/Message/MessageContent.tsx
- message avatar error
- message content avatar 에러 해결
- close #514
=> 🐛 [BugFix] message avatar error

backend/src/game/game.gateway.ts
- bar 이동 range 제한
- bar 의 y 범위를 최대값으로 조정합니다.
- close #522
=> :bug: [BugFix] Add range check to bar

frontend/src/App.tsx, frontend/src/DebugObserver.tsx, frontend/src/hooks/game/useGameStart.tsx, frontend/src/hooks/useCanvas.tsx, frontend/src/layout/GameLayout/GameLayout.tsx, frontend/src/pages/GamePage/GamePage.tsx, frontend/src/pages/GamePage/GameResultModal/GameResultModal.tsx, frontend/src/pages/GamePage/usePingPongGame.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/pages/LobbyPage/LobbyPage.tsx, frontend/src/stores/gameState.ts, frontend/vite.config.ts
- player bar overflow error 수정
- player bar overflow error 수정
- 빌드할때 console.log 제거
- 게임 유저 보이는 뷰 추가
- 게임 끝났을 때 useChannel refetch 업데이트
- close #487
- close #519
=> 🐛 [BugFix] Player bar

frontend/src/pages/ProfilePage/ProfilePage.tsx
Not updating profile page when url move
- url이 바뀌면 update 되도록 고쳤습니다.
https://github.com/GhostPangPang/GhostPong/issues/530
=> 🐛[BugFix] Not updating profile page when url move

backend/src/auth/auth.controller.ts, backend/src/auth/guard/two-fa.guard.ts, backend/src/channel/channel.service.spec.ts, backend/src/channel/channel.service.ts, types/user/socket/channel-invited.interface.ts, types/user/socket/index.ts
- `channel-invited` event dto 수정 (`channelId` 추가)
- dto 수정
- 2fa token 복구 (로그인에서 userId 정보를 담은 토큰이 필요함)
=> 🐛 [BugFix] Modify channel-invited event dto

frontend/src/pages/GamePage/usePingPongGame.tsx, frontend/src/pages/GameReadyPage/ChatBox/ChatInput.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx
- game ready reload error
- chat div overflow error
- game ready reload error
- chat div overflow error
- close #535
=> 🐛 [BugFix] game ready reload error

backend/src/game/game.gateway.ts, backend/src/game/game.service.ts, frontend/src/hooks/game/useGameStart.tsx, frontend/src/pages/GamePage/GamePage.tsx, frontend/src/pages/GamePage/usePingPongGame.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/stores/gameState.ts, types/game/socket/game-start.interface.ts
- 어떤 모드인지 채널 유저들에게 broadcast 해주는 로직 추가
- 모드 별 전환할때마다 있었던 bar 모양 이슈 해결
- mode `game-start` socket event 에서 broadcast
- close #511
=> 🐛 [BugFix] Mode broadcast

frontend/src/SocketHandler.tsx
- 플레이어 중 한명이 나갔을 때 에러
- 플레이어 중 한명이 나갔을 때 에러
- close #549
=> :bug: [BugFix] player out error

frontend/src/libs/utils/itemgenerator.tsx
Fix blocked 원래 됐었는데!!!!!!ㅋㅋㅋㅋㅋㅋㅋㅋ
=> 🐛 [BugFix]  Fix blocked

backend/src/channel/channel.service.ts, types/user/socket/channel-invited.interface.ts
- invite channel dto 수정
- channel `mode`, `password` 추가
=> 🐛 [BugFix] Modify ChannelInvited dto 

backend/src/channel/channel.service.ts, types/user/socket/channel-invited.interface.ts
=> 🐛 [BugFix] Restore ChannelInvited dto

types/user/socket/channel-invited.interface.ts
- channel type import error
- channel type import error
=> :bug: [BugFix] Delete channel import error

frontend/src/pages/GamePage/GameResultModal/GameResultModal.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/stores/gameState.ts
- GameResultModal 에 버튼 countdown 추가
- GameResultModal 에 버튼 countdown 추가
- 5초내에 아무버튼도 안누를시 대기페이지로 이동
- close #483
=> :sparkles: [Feaure] Add countdown GameResultModal

backend/src/channel/channel.controller.ts, backend/src/channel/channel.service.ts
=> :sparkles: [Feature] Add join invited channel api

frontend/src/SocketHandler.tsx, frontend/src/constants/event.ts, frontend/src/hooks/channel/useChannel.tsx, frontend/src/layout/GameLayout/GameSideBar.tsx, frontend/src/pages/GameReadyPage/ChatBox/ChatBox.tsx, frontend/src/pages/GameReadyPage/ChatBox/Chatcontent.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx
Invite 하는거 추가되었습니당
- invite 하는거 추가
- Sidebar 친구 패치
- chat csss 고침
https://github.com/GhostPangPang/GhostPong/issues/528
https://github.com/GhostPangPang/GhostPong/issues/520
https://github.com/GhostPangPang/GhostPong/issues/478
https://github.com/GhostPangPang/GhostPong/issues/523
=> ✨ [Feature] Invite channel connect

frontend/src/pages/GamePage/GameResultModal/GameResultModal.tsx, frontend/src/pages/GameReadyPage/ChatBox/ChatInput.tsx, frontend/src/pages/MessagePage/Message/MessageInput.tsx
- Random game timeout 에러 해결
- 5초 후 
- 랜덤이면 -> 로비페이지로 나가기
- 채널이면 -> 대기페이지로 나가기
- 메세지 input 오버플로우 에러 수정
- close #560
=> 🐛 [BugFix] random error

frontend/src/pages/MessagePage/Message/MessageContent.tsx
- 메세지 페이지 이미지 반대로 렌더링 되는 이슈 해결 
- 메세지 이미지 반대로 보이는 에러 해결
- close #564
=> :bug: [BugFix] messagePage profile img change error

frontend/src/SocketHandler.tsx, frontend/src/hooks/blocked/useBlocked.tsx, frontend/src/pages/GameReadyPage/ChatBox/Chatcontent.tsx, frontend/src/pages/GameReadyPage/GameReadyPage.tsx, frontend/src/stores/userInfoState.ts
- blocked error
- blocked error 수정
- channel 에 blocked 하자마자 안보이게 구현
- close #568
=> 🐛 [BugFix] blocked error

README.md
=> 📝 [Docs] Update README.md

backend/src/auth/auth.service.ts
- token 에러 수정
- `ERROR [ExceptionsHandler] The provided authorization` 에러 발생
- 잘못된 token option 수정해서 해결
=> :bug: [BugFix] Auth token error

.github/workflows/chromatic.yml, .github/workflows/frontend-build.yml
- default 브랜치를 develop 으로 바꾸면서 프론트엔드 ci 브랜치 수정
=> :hammer: [Refactor] Change ci branch to develop

.dockerignore, .gitignore, backend/.dockerignore
- `dockerignore` 파일 추가
- 이전 `gitignore` 과 `dockerignore` 정리
=> 🐛  [Hotfix] Add dockerignore

.dockerignore, .github/workflows/docker-cd.yml
- `docker-cd.yml` 업데이트
- 기존의 `docker compose build && push` 에서 각 파일 빌드 푸쉬로 수정
=> 🐛 [Hotfix] Update docker cd

.github/workflows/docker-cd.yml, frontend/Dockerfile, frontend/src/pages/MessagePage/BlockModal/BlockModal.tsx, frontend/src/pages/MessagePage/FriendsModal/FriendsModal.tsx
=> Revert ":bug: [HotFix] Fix docker-cd.yml"

frontend/src/App.tsx, frontend/src/pages/MessagePage/BlockModal/BlockModal.tsx, frontend/src/pages/MessagePage/FriendsModal/FriendsModal.tsx, frontend/src/pages/SignInPage/index.tsx, frontend/src/pages/SignUpPage/index.tsx, frontend/src/pages/index.ts
- 간단한 로컬 로그인/회원가입 페이지를 만들었습니다.
- login/signup api 연결
- state 관리
- 그 외, Exception 처리 및 세부사항은 업데이트 예정입니다. (error view, validations)
- close #593
=> :sparkles: [Feature] Update login/signup pages

.github/workflows/docker-cd.yml
- github action workflow dispatch 설정
=> 💚 [Chore] github action workflow dispatch 설정

.github/workflows/docker-cd.yml
=> :green_heart: [Chore] main push 트리거 cd action 제거

backend/src/auth/guard/user.guard.ts
guard 불필요한 경우에 대한 검증 로직 rollback
=> :green_heart: [Chore] skip user guard rollback

backend/src/auth/guard/user.guard.ts
=> 💚 [Release] skip guard 검증 로직 롤백
